#################### Druid数据源公共参数配置 ####################
initialSize: 5
minIdle: 5
maxIdle: 100
maxActive: 20
maxWait: 60000
timeBetweenEvictionRunsMillis: 60000
minEvictableIdleTimeMillis: 300000
#################### Druid数据源公共参数配置 ####################
sharding:
  jdbc:
    config:
      sharding:
        ### 未配置分片规则的表将通过默认数据源定位-适用于单库单表，该表无需配置分片规则
        default-data-source-name: ds0
        props:
          ### 打印sql日志
          sql:
            show: true
    datasource:
      ### 数据源，多数据源以逗号分隔
      names: ds0
      ### ds0库
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.181.128:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root3306
        initialSize: ${initialSize}
        minIdle: ${minIdle}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        validationQuery: SELECT 1 FROM DUAL
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}






