spring:
#################### 数据源配置 ####################
  profiles:
    include: sjdbc-config-dev
#################### Redis配置 ####################
  redis:
    database: 0
    host: 121.40.94.96
    password: 666666
    port: 6379
    timeout: 5000ms
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms











