server:
  port: 8888
spring:
  profiles:
      active: dev
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /**
    view:
      prefix: /view/
      suffix: .html




