server:
  port: 8888
spring:
  profiles:
      active: dev
  application:
    name: cp-web
  main:
    allow-bean-definition-overriding: true

#################### MVC配置 ####################
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /**
    view:
      prefix: /view/
      suffix: .html
#################### mybatis配置 ####################
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:mybatis-config.xml
#################### mybatis配置 ####################
logging:
  level:
    com.hb.cp.web: info
  path: /cplog/




