spring:
#################### Druid数据源配置 ####################
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/cpweb?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root3306
      driverClassName: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
#################### Redis配置 ####################
  redis:
    database: 0
    host: 121.40.94.96
    password: 666666
    port: 6379
    timeout: 5000ms
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms





