spring:
  datasource:
      url: jdbc:mysql://localhost:3306/cpweb?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root3306
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
      database: MYSQL
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          use_sql_comments: true




